spring:
  application:
    name: orders
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      group-id: stock
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: com.dissanayake.fuel.*
    streams:
      properties:
        commit.interval.ms: 0
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        spring.json.trusted.packages: com.dissanayake.fuel.*
      state-dir: /tmp/kafka-streams/
    topic:
      name: order_topic
  datasource:
    url: jdbc:mysql://localhost:3306/AllocationDB?createDatabaseIfNotExist=true
    username: root
    password: 1234
    river-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
server:
  port: 8083
